import type {
  Confidence,
  Finding,
  FindingCategory,
  RuleReference,
  Severity,
} from "../types.js";

export const RULES_VERSION = "2026.07";

interface RuleDefinition {
  severity: Severity;
  confidence: Confidence;
  category: FindingCategory;
  title: string;
  recommendation: string;
  references: RuleReference[];
}

const MCP_SCHEMA =
  "https://modelcontextprotocol.io/specification/2025-11-25/schema";
const MCP_SECURITY =
  "https://modelcontextprotocol.io/docs/tutorials/security/security_best_practices";
const MCP_AUTH =
  "https://modelcontextprotocol.io/specification/2025-11-25/basic/authorization";

export const RULES = {
  EXEC001: {
    severity: "info",
    confidence: "high",
    category: "execution",
    title: "Dynamic discovery was not executed",
    recommendation: "Review the target, then rerun with --execute in a disposable environment.",
    references: [{ label: "MCP security best practices", url: MCP_SECURITY }],
  },
  EXEC002: {
    severity: "medium",
    confidence: "high",
    category: "execution",
    title: "Dynamic discovery failed",
    recommendation: "Review the bounded error, target logs, authorization, and transport settings.",
    references: [{ label: "MCP Inspector", url: "https://modelcontextprotocol.io/docs/tools/inspector" }],
  },
  LAUNCH001: {
    severity: "high",
    confidence: "high",
    category: "execution",
    title: "Target is launched through a general-purpose shell",
    recommendation: "Launch a fixed executable directly and pass arguments as an array.",
    references: [{ label: "MCP security best practices", url: MCP_SECURITY }],
  },
  LAUNCH002: {
    severity: "medium",
    confidence: "high",
    category: "execution",
    title: "Target may download executable code at startup",
    recommendation: "Pin and install the package before scanning, then execute the local binary.",
    references: [{ label: "MCP security best practices", url: MCP_SECURITY }],
  },
  LAUNCH003: {
    severity: "high",
    confidence: "medium",
    category: "execution",
    title: "Suspicious launcher argument",
    recommendation: "Replace the launcher with a fixed, reviewable command.",
    references: [{ label: "MCP security best practices", url: MCP_SECURITY }],
  },
  TOOL001: {
    severity: "high",
    confidence: "high",
    category: "protocol",
    title: "Tool name exceeds the compatibility limit",
    recommendation: "Use a stable tool name with at most 64 characters.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  TOOL002: {
    severity: "medium",
    confidence: "high",
    category: "metadata",
    title: "Tool description is missing",
    recommendation: "Describe the tool's precise behavior and when it is appropriate.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  TOOL003: {
    severity: "high",
    confidence: "medium",
    category: "metadata",
    title: "Tool description contains a prompt-injection-like instruction",
    recommendation: "Describe functionality only; remove behavioral or hidden instructions.",
    references: [{ label: "MCP security best practices", url: MCP_SECURITY }],
  },
  TOOL004: {
    severity: "low",
    confidence: "high",
    category: "metadata",
    title: "Tool display title is missing",
    recommendation: "Set top-level title or annotations.title to a short human-readable value.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  TOOL005: {
    severity: "medium",
    confidence: "high",
    category: "metadata",
    title: "Tool safety hints are not explicit",
    recommendation:
      "Declare readOnlyHint, destructiveHint, idempotentHint, and openWorldHint explicitly.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  TOOL006: {
    severity: "high",
    confidence: "medium",
    category: "behavior",
    title: "Potentially destructive tool is not marked destructive",
    recommendation: "Set destructiveHint to true and keep the operation narrowly scoped.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  TOOL007: {
    severity: "medium",
    confidence: "medium",
    category: "behavior",
    title: "Read-like tool is explicitly marked as writable",
    recommendation: "Split reading and mutation into separate tools with accurate hints.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  TOOL008: {
    severity: "high",
    confidence: "high",
    category: "schema",
    title: "Tool mixes read and write HTTP operations",
    recommendation: "Split read operations from create, update, and delete tools.",
    references: [{ label: "MCP tools", url: MCP_SCHEMA }],
  },
  TOOL009: {
    severity: "low",
    confidence: "high",
    category: "schema",
    title: "Input schema accepts undeclared properties",
    recommendation: "Reject unknown input fields when the server framework supports it.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  TOOL010: {
    severity: "high",
    confidence: "high",
    category: "metadata",
    title: "Tool annotations contradict each other",
    recommendation: "Do not mark a read-only tool as destructive.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  TOOL011: {
    severity: "low",
    confidence: "high",
    category: "metadata",
    title: "Open-world behavior is not explicit",
    recommendation: "Declare openWorldHint so clients can apply an appropriate approval policy.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  TOOL012: {
    severity: "low",
    confidence: "high",
    category: "schema",
    title: "Tool output schema is missing",
    recommendation: "Declare outputSchema for structured and independently validated results.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  TOOL013: {
    severity: "medium",
    confidence: "high",
    category: "schema",
    title: "Required input is not declared as a property",
    recommendation: "Every required field must have a corresponding properties entry.",
    references: [{ label: "JSON Schema 2020-12", url: "https://json-schema.org/draft/2020-12" }],
  },
  TOOL014: {
    severity: "high",
    confidence: "high",
    category: "schema",
    title: "Tool schema exceeds safe inspection complexity",
    recommendation: "Reduce schema depth and size to keep clients responsive.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  SERVER001: {
    severity: "medium",
    confidence: "medium",
    category: "metadata",
    title: "Server instructions contain prompt-injection-like text",
    recommendation: "Keep server instructions descriptive and remove behavioral overrides.",
    references: [{ label: "MCP security best practices", url: MCP_SECURITY }],
  },
  SERVER002: {
    severity: "low",
    confidence: "high",
    category: "metadata",
    title: "Server implementation version is missing",
    recommendation: "Advertise a stable server version for incident response and compatibility.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  SERVER003: {
    severity: "high",
    confidence: "high",
    category: "protocol",
    title: "Negotiated MCP protocol version is not recognized",
    recommendation: "Use a published MCP protocol version or an explicitly enabled preview.",
    references: [{ label: "MCP specification", url: "https://modelcontextprotocol.io/specification/" }],
  },
  RESOURCE001: {
    severity: "low",
    confidence: "high",
    category: "metadata",
    title: "Resource description is missing",
    recommendation: "Describe the resource's content, scope, and sensitivity.",
    references: [{ label: "MCP resources", url: MCP_SCHEMA }],
  },
  RESOURCE002: {
    severity: "medium",
    confidence: "medium",
    category: "behavior",
    title: "Resource exposes a local filesystem URI",
    recommendation: "Document and narrowly scope filesystem access exposed through resources.",
    references: [{ label: "MCP security best practices", url: MCP_SECURITY }],
  },
  RESOURCE003: {
    severity: "high",
    confidence: "high",
    category: "metadata",
    title: "Resource URI contains embedded credentials",
    recommendation: "Remove credentials from URIs and use a dedicated authorization mechanism.",
    references: [{ label: "MCP authorization", url: MCP_AUTH }],
  },
  RESOURCE004: {
    severity: "medium",
    confidence: "high",
    category: "protocol",
    title: "Resource declares an excessive size",
    recommendation: "Bound resource size and paginate or stream large content safely.",
    references: [{ label: "MCP resources", url: MCP_SCHEMA }],
  },
  PROMPT001: {
    severity: "low",
    confidence: "high",
    category: "metadata",
    title: "Prompt description is missing",
    recommendation: "Describe the prompt's intended use and expected arguments.",
    references: [{ label: "MCP prompts", url: MCP_SCHEMA }],
  },
  PROMPT002: {
    severity: "high",
    confidence: "medium",
    category: "metadata",
    title: "Prompt metadata contains prompt-injection-like text",
    recommendation: "Remove instruction overrides, concealment, and safety bypass language.",
    references: [{ label: "MCP security best practices", url: MCP_SECURITY }],
  },
  AUTH001: {
    severity: "high",
    confidence: "high",
    category: "transport",
    title: "Remote MCP endpoint does not use HTTPS",
    recommendation: "Use HTTPS for every non-loopback MCP and authorization endpoint.",
    references: [{ label: "MCP authorization", url: MCP_AUTH }],
  },
  AUTH002: {
    severity: "critical",
    confidence: "high",
    category: "authentication",
    title: "Remote MCP URL contains embedded credentials",
    recommendation: "Remove credentials from the URL and rotate the exposed credential.",
    references: [{ label: "MCP authorization", url: MCP_AUTH }],
  },
  AUTH003: {
    severity: "medium",
    confidence: "high",
    category: "authentication",
    title: "Protected resource metadata is unavailable",
    recommendation: "Publish RFC 9728 protected resource metadata for the MCP endpoint.",
    references: [{ label: "MCP authorization", url: MCP_AUTH }],
  },
  AUTH004: {
    severity: "high",
    confidence: "high",
    category: "authentication",
    title: "Protected resource identifier does not match the MCP endpoint",
    recommendation: "Bind tokens to the exact MCP resource identifier.",
    references: [{ label: "MCP authorization", url: MCP_AUTH }],
  },
  AUTH005: {
    severity: "high",
    confidence: "high",
    category: "authentication",
    title: "Authorization server endpoint does not use HTTPS",
    recommendation: "Serve authorization metadata and endpoints over HTTPS.",
    references: [{ label: "MCP authorization", url: MCP_AUTH }],
  },
  AUTH006: {
    severity: "high",
    confidence: "high",
    category: "authentication",
    title: "Authorization server does not advertise PKCE S256",
    recommendation: "Require PKCE with the S256 code challenge method.",
    references: [{ label: "MCP authorization", url: MCP_AUTH }],
  },
  AUTH007: {
    severity: "high",
    confidence: "high",
    category: "authentication",
    title: "Protected resource metadata lists no authorization server",
    recommendation: "Publish at least one explicit authorization server identifier.",
    references: [{ label: "MCP authorization", url: MCP_AUTH }],
  },
  AUTH008: {
    severity: "medium",
    confidence: "high",
    category: "authentication",
    title: "Authorization server metadata is unavailable",
    recommendation: "Publish RFC 8414 or OpenID Connect discovery metadata.",
    references: [{ label: "MCP authorization", url: MCP_AUTH }],
  },
  SANDBOX001: {
    severity: "high",
    confidence: "high",
    category: "sandbox",
    title: "Dynamic execution is not OS-sandboxed",
    recommendation: "Use the Docker sandbox adapter or a disposable isolated host.",
    references: [{ label: "MCP security best practices", url: MCP_SECURITY }],
  },
  SANDBOX002: {
    severity: "medium",
    confidence: "high",
    category: "sandbox",
    title: "Sandbox image is not pinned by digest",
    recommendation: "Pin the container image to an immutable sha256 digest.",
    references: [
      {
        label: "OpenSSF Scorecard pinned dependencies",
        url: "https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies",
      },
    ],
  },
  BEHAVIOR001: {
    severity: "critical",
    confidence: "high",
    category: "behavior",
    title: "Tool result disclosed the synthetic canary",
    recommendation: "Remove undeclared filesystem or environment access and rotate affected secrets.",
    references: [{ label: "MCP security best practices", url: MCP_SECURITY }],
  },
  BEHAVIOR002: {
    severity: "medium",
    confidence: "medium",
    category: "behavior",
    title: "Idempotent tool returned inconsistent results",
    recommendation: "Make repeated identical calls stable or remove idempotentHint.",
    references: [{ label: "MCP schema reference", url: MCP_SCHEMA }],
  },
  BEHAVIOR003: {
    severity: "high",
    confidence: "high",
    category: "behavior",
    title: "Explicit synthetic tool call failed",
    recommendation: "Review the bounded error and make failure behavior deterministic.",
    references: [{ label: "MCP tools", url: MCP_SCHEMA }],
  },
  BEHAVIOR004: {
    severity: "critical",
    confidence: "high",
    category: "sandbox",
    title: "Read-only canary changed during execution",
    recommendation: "Stop using the sandbox adapter and investigate an isolation failure.",
    references: [{ label: "MCP security best practices", url: MCP_SECURITY }],
  },
  BEHAVIOR005: {
    severity: "high",
    confidence: "high",
    category: "behavior",
    title: "Tool result exceeds the configured response limit",
    recommendation: "Bound, paginate, or stream tool results within the configured policy.",
    references: [{ label: "MCP tools", url: MCP_SCHEMA }],
  },
} as const satisfies Record<string, RuleDefinition>;

export type RuleId = keyof typeof RULES;

export function createFinding(id: RuleId, evidence: string, location?: string): Finding {
  const rule = RULES[id];
  return {
    id,
    severity: rule.severity,
    confidence: rule.confidence,
    category: rule.category,
    title: rule.title,
    evidence,
    recommendation: rule.recommendation,
    references: [...rule.references],
    ...(location === undefined ? {} : { location }),
  };
}
